// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Read from environment variables
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "";

// Create client with empty strings as fallback to prevent build-time crashes
// Runtime validation happens in first actual usage
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);

// Helper to validate connection before critical operations
export function validateSupabaseConfig(): { valid: boolean; error?: string } {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    return {
      valid: false,
      error: "Missing Supabase environment variables. Please check your .env.local file.",
    };
  }
  
  try {
    new URL(SUPABASE_URL);
    return { valid: true };
  } catch {
    return {
      valid: false,
      error: "Invalid Supabase URL format.",
    };
  }
}